print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/millerklitsner/Documents/GitHub/RealShadowsShine/Shade Manipulation Game/Assets/Models/terrrain.mb"`)
{		
	file -o "/Users/millerklitsner/Documents/GitHub/RealShadowsShine/Shade Manipulation Game/Assets/Models/terrrain.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/millerklitsner/Documents/GitHub/RealShadowsShine/Shade Manipulation Game/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/millerklitsner/Documents/GitHub/RealShadowsShine/Shade Manipulation Game/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/millerklitsner/Documents/GitHub/RealShadowsShine/Shade Manipulation Game/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
